In [7]:
Q=[]
while True:
    print("1. Insert   2. Delete   3. Display   4. Exit")
    ch=int(input("Enter choice: "))
    if ch==1:
        bid=int(input("Enter book id: "))
        bname=input("Enter book name: ")
        aut=input("Enter author name: ")
        Q.append([bid,bname,aut])
    elif ch==2:
        if Q==[]:
            print("Queue is empty...")
        else:
            bid,bname,aut=Q.pop(0)
            print("Deleted book",bid,bname)
    elif ch==3:
        if Q==[]:
            print("Queue is empty...")
        else:
            for i in range(len(Q)):
                if i==0:
                    print(Q[i],"<----First value")
                else:
                    print(Q[i])
    elif ch==4:
        break
    else:
        print("Invalid Input!!\nEnter choice again...")
    print()

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 2
Queue is empty...

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 3
Queue is empty...

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 1
Enter book id: 123
Enter book name: The Alchemist
Enter author name: Paulo Coelho

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 1
Enter book id: 456
Enter book name: Percy Jackson
Enter author name: Roald Dahl

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 1
Enter book id: 789
Enter book name: Harry Potter
Enter author name: JK Rowling

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 3
[123, 'The Alchemist', 'Paulo Coelho'] <----First value
[456, 'Percy Jackson', 'Roald Dahl']
[789, 'Harry Potter', 'JK Rowling']

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 2
Deleted book 123 The Alchemist

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 3
[456, 'Percy Jackson', 'Roald Dahl'] <----First value
[789, 'Harry Potter', 'JK Rowling']

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 2
Deleted book 456 Percy Jackson

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 2
Deleted book 789 Harry Potter

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 2
Queue is empty...

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 3
Queue is empty...

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 5
Invalid Input!!
Enter choice again...

1. Insert   2. Delete   3. Display   4. Exit
Enter choice: 4